// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: add_contact_request.proto

#include "add_contact_request.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_add_5fcontact_5frequest_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_AddContactReq_Phone_add_5fcontact_5frequest_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_add_5fcontact_5frequest_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_AddContactReq_RemarkEntry_DoNotUse_add_5fcontact_5frequest_2eproto;
namespace add_contact_req {
class AddContactReq_PhoneDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<AddContactReq_Phone> _instance;
} _AddContactReq_Phone_default_instance_;
class AddContactReq_RemarkEntry_DoNotUseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<AddContactReq_RemarkEntry_DoNotUse> _instance;
} _AddContactReq_RemarkEntry_DoNotUse_default_instance_;
class AddContactReqDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<AddContactReq> _instance;
} _AddContactReq_default_instance_;
}  // namespace add_contact_req
static void InitDefaultsscc_info_AddContactReq_add_5fcontact_5frequest_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::add_contact_req::_AddContactReq_default_instance_;
    new (ptr) ::add_contact_req::AddContactReq();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::add_contact_req::AddContactReq::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_AddContactReq_add_5fcontact_5frequest_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 2, 0, InitDefaultsscc_info_AddContactReq_add_5fcontact_5frequest_2eproto}, {
      &scc_info_AddContactReq_Phone_add_5fcontact_5frequest_2eproto.base,
      &scc_info_AddContactReq_RemarkEntry_DoNotUse_add_5fcontact_5frequest_2eproto.base,}};

static void InitDefaultsscc_info_AddContactReq_Phone_add_5fcontact_5frequest_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::add_contact_req::_AddContactReq_Phone_default_instance_;
    new (ptr) ::add_contact_req::AddContactReq_Phone();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::add_contact_req::AddContactReq_Phone::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_AddContactReq_Phone_add_5fcontact_5frequest_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_AddContactReq_Phone_add_5fcontact_5frequest_2eproto}, {}};

static void InitDefaultsscc_info_AddContactReq_RemarkEntry_DoNotUse_add_5fcontact_5frequest_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::add_contact_req::_AddContactReq_RemarkEntry_DoNotUse_default_instance_;
    new (ptr) ::add_contact_req::AddContactReq_RemarkEntry_DoNotUse();
  }
  ::add_contact_req::AddContactReq_RemarkEntry_DoNotUse::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_AddContactReq_RemarkEntry_DoNotUse_add_5fcontact_5frequest_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_AddContactReq_RemarkEntry_DoNotUse_add_5fcontact_5frequest_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_add_5fcontact_5frequest_2eproto[3];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_add_5fcontact_5frequest_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_add_5fcontact_5frequest_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_add_5fcontact_5frequest_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::add_contact_req::AddContactReq_Phone, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::add_contact_req::AddContactReq_Phone, number_),
  PROTOBUF_FIELD_OFFSET(::add_contact_req::AddContactReq_Phone, type_),
  PROTOBUF_FIELD_OFFSET(::add_contact_req::AddContactReq_RemarkEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::add_contact_req::AddContactReq_RemarkEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::add_contact_req::AddContactReq_RemarkEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::add_contact_req::AddContactReq_RemarkEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::add_contact_req::AddContactReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::add_contact_req::AddContactReq, name_),
  PROTOBUF_FIELD_OFFSET(::add_contact_req::AddContactReq, age_),
  PROTOBUF_FIELD_OFFSET(::add_contact_req::AddContactReq, phone_number_),
  PROTOBUF_FIELD_OFFSET(::add_contact_req::AddContactReq, remark_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::add_contact_req::AddContactReq_Phone)},
  { 7, 14, sizeof(::add_contact_req::AddContactReq_RemarkEntry_DoNotUse)},
  { 16, -1, sizeof(::add_contact_req::AddContactReq)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::add_contact_req::_AddContactReq_Phone_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::add_contact_req::_AddContactReq_RemarkEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::add_contact_req::_AddContactReq_default_instance_),
};

const char descriptor_table_protodef_add_5fcontact_5frequest_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\031add_contact_request.proto\022\017add_contact"
  "_req\"\306\002\n\rAddContactReq\022\014\n\004name\030\001 \001(\t\022\013\n\003"
  "age\030\002 \001(\005\022:\n\014phone_number\030\003 \003(\0132$.add_co"
  "ntact_req.AddContactReq.Phone\022:\n\006remark\030"
  "\004 \003(\0132*.add_contact_req.AddContactReq.Re"
  "markEntry\032s\n\005Phone\022\016\n\006number\030\001 \001(\t\022<\n\004ty"
  "pe\030\002 \001(\0162..add_contact_req.AddContactReq"
  ".Phone.PhoneType\"\034\n\tPhoneType\022\006\n\002MP\020\000\022\007\n"
  "\003TEL\020\001\032-\n\013RemarkEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005va"
  "lue\030\002 \001(\t:\0028\001b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_add_5fcontact_5frequest_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_add_5fcontact_5frequest_2eproto_sccs[3] = {
  &scc_info_AddContactReq_add_5fcontact_5frequest_2eproto.base,
  &scc_info_AddContactReq_Phone_add_5fcontact_5frequest_2eproto.base,
  &scc_info_AddContactReq_RemarkEntry_DoNotUse_add_5fcontact_5frequest_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_add_5fcontact_5frequest_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_add_5fcontact_5frequest_2eproto = {
  false, false, descriptor_table_protodef_add_5fcontact_5frequest_2eproto, "add_contact_request.proto", 381,
  &descriptor_table_add_5fcontact_5frequest_2eproto_once, descriptor_table_add_5fcontact_5frequest_2eproto_sccs, descriptor_table_add_5fcontact_5frequest_2eproto_deps, 3, 0,
  schemas, file_default_instances, TableStruct_add_5fcontact_5frequest_2eproto::offsets,
  file_level_metadata_add_5fcontact_5frequest_2eproto, 3, file_level_enum_descriptors_add_5fcontact_5frequest_2eproto, file_level_service_descriptors_add_5fcontact_5frequest_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_add_5fcontact_5frequest_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_add_5fcontact_5frequest_2eproto)), true);
namespace add_contact_req {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* AddContactReq_Phone_PhoneType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_add_5fcontact_5frequest_2eproto);
  return file_level_enum_descriptors_add_5fcontact_5frequest_2eproto[0];
}
bool AddContactReq_Phone_PhoneType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr AddContactReq_Phone_PhoneType AddContactReq_Phone::MP;
constexpr AddContactReq_Phone_PhoneType AddContactReq_Phone::TEL;
constexpr AddContactReq_Phone_PhoneType AddContactReq_Phone::PhoneType_MIN;
constexpr AddContactReq_Phone_PhoneType AddContactReq_Phone::PhoneType_MAX;
constexpr int AddContactReq_Phone::PhoneType_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)

// ===================================================================

void AddContactReq_Phone::InitAsDefaultInstance() {
}
class AddContactReq_Phone::_Internal {
 public:
};

AddContactReq_Phone::AddContactReq_Phone(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:add_contact_req.AddContactReq.Phone)
}
AddContactReq_Phone::AddContactReq_Phone(const AddContactReq_Phone& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  number_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_number().empty()) {
    number_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_number(),
      GetArena());
  }
  type_ = from.type_;
  // @@protoc_insertion_point(copy_constructor:add_contact_req.AddContactReq.Phone)
}

void AddContactReq_Phone::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_AddContactReq_Phone_add_5fcontact_5frequest_2eproto.base);
  number_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  type_ = 0;
}

AddContactReq_Phone::~AddContactReq_Phone() {
  // @@protoc_insertion_point(destructor:add_contact_req.AddContactReq.Phone)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void AddContactReq_Phone::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  number_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void AddContactReq_Phone::ArenaDtor(void* object) {
  AddContactReq_Phone* _this = reinterpret_cast< AddContactReq_Phone* >(object);
  (void)_this;
}
void AddContactReq_Phone::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void AddContactReq_Phone::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const AddContactReq_Phone& AddContactReq_Phone::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_AddContactReq_Phone_add_5fcontact_5frequest_2eproto.base);
  return *internal_default_instance();
}


void AddContactReq_Phone::Clear() {
// @@protoc_insertion_point(message_clear_start:add_contact_req.AddContactReq.Phone)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  number_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  type_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AddContactReq_Phone::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string number = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_number();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "add_contact_req.AddContactReq.Phone.number"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .add_contact_req.AddContactReq.Phone.PhoneType type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_type(static_cast<::add_contact_req::AddContactReq_Phone_PhoneType>(val));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* AddContactReq_Phone::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:add_contact_req.AddContactReq.Phone)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string number = 1;
  if (this->number().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_number().data(), static_cast<int>(this->_internal_number().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "add_contact_req.AddContactReq.Phone.number");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_number(), target);
  }

  // .add_contact_req.AddContactReq.Phone.PhoneType type = 2;
  if (this->type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      2, this->_internal_type(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:add_contact_req.AddContactReq.Phone)
  return target;
}

size_t AddContactReq_Phone::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:add_contact_req.AddContactReq.Phone)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string number = 1;
  if (this->number().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_number());
  }

  // .add_contact_req.AddContactReq.Phone.PhoneType type = 2;
  if (this->type() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_type());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void AddContactReq_Phone::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:add_contact_req.AddContactReq.Phone)
  GOOGLE_DCHECK_NE(&from, this);
  const AddContactReq_Phone* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<AddContactReq_Phone>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:add_contact_req.AddContactReq.Phone)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:add_contact_req.AddContactReq.Phone)
    MergeFrom(*source);
  }
}

void AddContactReq_Phone::MergeFrom(const AddContactReq_Phone& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:add_contact_req.AddContactReq.Phone)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.number().size() > 0) {
    _internal_set_number(from._internal_number());
  }
  if (from.type() != 0) {
    _internal_set_type(from._internal_type());
  }
}

void AddContactReq_Phone::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:add_contact_req.AddContactReq.Phone)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AddContactReq_Phone::CopyFrom(const AddContactReq_Phone& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:add_contact_req.AddContactReq.Phone)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AddContactReq_Phone::IsInitialized() const {
  return true;
}

void AddContactReq_Phone::InternalSwap(AddContactReq_Phone* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  number_.Swap(&other->number_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(type_, other->type_);
}

::PROTOBUF_NAMESPACE_ID::Metadata AddContactReq_Phone::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

AddContactReq_RemarkEntry_DoNotUse::AddContactReq_RemarkEntry_DoNotUse() {}
AddContactReq_RemarkEntry_DoNotUse::AddContactReq_RemarkEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void AddContactReq_RemarkEntry_DoNotUse::MergeFrom(const AddContactReq_RemarkEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata AddContactReq_RemarkEntry_DoNotUse::GetMetadata() const {
  return GetMetadataStatic();
}
void AddContactReq_RemarkEntry_DoNotUse::MergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::Message& other) {
  ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom(other);
}


// ===================================================================

void AddContactReq::InitAsDefaultInstance() {
}
class AddContactReq::_Internal {
 public:
};

AddContactReq::AddContactReq(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  phone_number_(arena),
  remark_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:add_contact_req.AddContactReq)
}
AddContactReq::AddContactReq(const AddContactReq& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      phone_number_(from.phone_number_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  remark_.MergeFrom(from.remark_);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_name().empty()) {
    name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_name(),
      GetArena());
  }
  age_ = from.age_;
  // @@protoc_insertion_point(copy_constructor:add_contact_req.AddContactReq)
}

void AddContactReq::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_AddContactReq_add_5fcontact_5frequest_2eproto.base);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  age_ = 0;
}

AddContactReq::~AddContactReq() {
  // @@protoc_insertion_point(destructor:add_contact_req.AddContactReq)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void AddContactReq::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void AddContactReq::ArenaDtor(void* object) {
  AddContactReq* _this = reinterpret_cast< AddContactReq* >(object);
  (void)_this;
}
void AddContactReq::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void AddContactReq::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const AddContactReq& AddContactReq::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_AddContactReq_add_5fcontact_5frequest_2eproto.base);
  return *internal_default_instance();
}


void AddContactReq::Clear() {
// @@protoc_insertion_point(message_clear_start:add_contact_req.AddContactReq)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  phone_number_.Clear();
  remark_.Clear();
  name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  age_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AddContactReq::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "add_contact_req.AddContactReq.name"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 age = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          age_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .add_contact_req.AddContactReq.Phone phone_number = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_phone_number(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else goto handle_unusual;
        continue;
      // map<string, string> remark = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&remark_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* AddContactReq::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:add_contact_req.AddContactReq)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "add_contact_req.AddContactReq.name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  // int32 age = 2;
  if (this->age() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_age(), target);
  }

  // repeated .add_contact_req.AddContactReq.Phone phone_number = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_phone_number_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, this->_internal_phone_number(i), target, stream);
  }

  // map<string, string> remark = 4;
  if (!this->_internal_remark().empty()) {
    typedef ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::PROTOBUF_NAMESPACE_ID::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
          "add_contact_req.AddContactReq.RemarkEntry.key");
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
          p->second.data(), static_cast<int>(p->second.length()),
          ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
          "add_contact_req.AddContactReq.RemarkEntry.value");
      }
    };

    if (stream->IsSerializationDeterministic() &&
        this->_internal_remark().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->_internal_remark().size()]);
      typedef ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::size_type size_type;
      size_type n = 0;
      for (::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_iterator
          it = this->_internal_remark().begin();
          it != this->_internal_remark().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      for (size_type i = 0; i < n; i++) {
        target = AddContactReq_RemarkEntry_DoNotUse::Funcs::InternalSerialize(4, items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second, target, stream);
        Utf8Check::Check(&(*items[static_cast<ptrdiff_t>(i)]));
      }
    } else {
      for (::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_iterator
          it = this->_internal_remark().begin();
          it != this->_internal_remark().end(); ++it) {
        target = AddContactReq_RemarkEntry_DoNotUse::Funcs::InternalSerialize(4, it->first, it->second, target, stream);
        Utf8Check::Check(&(*it));
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:add_contact_req.AddContactReq)
  return target;
}

size_t AddContactReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:add_contact_req.AddContactReq)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .add_contact_req.AddContactReq.Phone phone_number = 3;
  total_size += 1UL * this->_internal_phone_number_size();
  for (const auto& msg : this->phone_number_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // map<string, string> remark = 4;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_remark_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_iterator
      it = this->_internal_remark().begin();
      it != this->_internal_remark().end(); ++it) {
    total_size += AddContactReq_RemarkEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  // string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // int32 age = 2;
  if (this->age() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_age());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void AddContactReq::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:add_contact_req.AddContactReq)
  GOOGLE_DCHECK_NE(&from, this);
  const AddContactReq* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<AddContactReq>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:add_contact_req.AddContactReq)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:add_contact_req.AddContactReq)
    MergeFrom(*source);
  }
}

void AddContactReq::MergeFrom(const AddContactReq& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:add_contact_req.AddContactReq)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  phone_number_.MergeFrom(from.phone_number_);
  remark_.MergeFrom(from.remark_);
  if (from.name().size() > 0) {
    _internal_set_name(from._internal_name());
  }
  if (from.age() != 0) {
    _internal_set_age(from._internal_age());
  }
}

void AddContactReq::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:add_contact_req.AddContactReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AddContactReq::CopyFrom(const AddContactReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:add_contact_req.AddContactReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AddContactReq::IsInitialized() const {
  return true;
}

void AddContactReq::InternalSwap(AddContactReq* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  phone_number_.InternalSwap(&other->phone_number_);
  remark_.Swap(&other->remark_);
  name_.Swap(&other->name_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(age_, other->age_);
}

::PROTOBUF_NAMESPACE_ID::Metadata AddContactReq::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace add_contact_req
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::add_contact_req::AddContactReq_Phone* Arena::CreateMaybeMessage< ::add_contact_req::AddContactReq_Phone >(Arena* arena) {
  return Arena::CreateMessageInternal< ::add_contact_req::AddContactReq_Phone >(arena);
}
template<> PROTOBUF_NOINLINE ::add_contact_req::AddContactReq_RemarkEntry_DoNotUse* Arena::CreateMaybeMessage< ::add_contact_req::AddContactReq_RemarkEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::add_contact_req::AddContactReq_RemarkEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::add_contact_req::AddContactReq* Arena::CreateMaybeMessage< ::add_contact_req::AddContactReq >(Arena* arena) {
  return Arena::CreateMessageInternal< ::add_contact_req::AddContactReq >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
