// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: add_contact_request.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_add_5fcontact_5frequest_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_add_5fcontact_5frequest_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_add_5fcontact_5frequest_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_add_5fcontact_5frequest_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_add_5fcontact_5frequest_2eproto;
namespace add_contact_req {
class AddContactReq;
class AddContactReqDefaultTypeInternal;
extern AddContactReqDefaultTypeInternal _AddContactReq_default_instance_;
class AddContactReq_Phone;
class AddContactReq_PhoneDefaultTypeInternal;
extern AddContactReq_PhoneDefaultTypeInternal _AddContactReq_Phone_default_instance_;
class AddContactReq_RemarkEntry_DoNotUse;
class AddContactReq_RemarkEntry_DoNotUseDefaultTypeInternal;
extern AddContactReq_RemarkEntry_DoNotUseDefaultTypeInternal _AddContactReq_RemarkEntry_DoNotUse_default_instance_;
}  // namespace add_contact_req
PROTOBUF_NAMESPACE_OPEN
template<> ::add_contact_req::AddContactReq* Arena::CreateMaybeMessage<::add_contact_req::AddContactReq>(Arena*);
template<> ::add_contact_req::AddContactReq_Phone* Arena::CreateMaybeMessage<::add_contact_req::AddContactReq_Phone>(Arena*);
template<> ::add_contact_req::AddContactReq_RemarkEntry_DoNotUse* Arena::CreateMaybeMessage<::add_contact_req::AddContactReq_RemarkEntry_DoNotUse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace add_contact_req {

enum AddContactReq_Phone_PhoneType : int {
  AddContactReq_Phone_PhoneType_MP = 0,
  AddContactReq_Phone_PhoneType_TEL = 1,
  AddContactReq_Phone_PhoneType_AddContactReq_Phone_PhoneType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  AddContactReq_Phone_PhoneType_AddContactReq_Phone_PhoneType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool AddContactReq_Phone_PhoneType_IsValid(int value);
constexpr AddContactReq_Phone_PhoneType AddContactReq_Phone_PhoneType_PhoneType_MIN = AddContactReq_Phone_PhoneType_MP;
constexpr AddContactReq_Phone_PhoneType AddContactReq_Phone_PhoneType_PhoneType_MAX = AddContactReq_Phone_PhoneType_TEL;
constexpr int AddContactReq_Phone_PhoneType_PhoneType_ARRAYSIZE = AddContactReq_Phone_PhoneType_PhoneType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* AddContactReq_Phone_PhoneType_descriptor();
template<typename T>
inline const std::string& AddContactReq_Phone_PhoneType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, AddContactReq_Phone_PhoneType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function AddContactReq_Phone_PhoneType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    AddContactReq_Phone_PhoneType_descriptor(), enum_t_value);
}
inline bool AddContactReq_Phone_PhoneType_Parse(
    const std::string& name, AddContactReq_Phone_PhoneType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<AddContactReq_Phone_PhoneType>(
    AddContactReq_Phone_PhoneType_descriptor(), name, value);
}
// ===================================================================

class AddContactReq_Phone PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:add_contact_req.AddContactReq.Phone) */ {
 public:
  inline AddContactReq_Phone() : AddContactReq_Phone(nullptr) {};
  virtual ~AddContactReq_Phone();

  AddContactReq_Phone(const AddContactReq_Phone& from);
  AddContactReq_Phone(AddContactReq_Phone&& from) noexcept
    : AddContactReq_Phone() {
    *this = ::std::move(from);
  }

  inline AddContactReq_Phone& operator=(const AddContactReq_Phone& from) {
    CopyFrom(from);
    return *this;
  }
  inline AddContactReq_Phone& operator=(AddContactReq_Phone&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const AddContactReq_Phone& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AddContactReq_Phone* internal_default_instance() {
    return reinterpret_cast<const AddContactReq_Phone*>(
               &_AddContactReq_Phone_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(AddContactReq_Phone& a, AddContactReq_Phone& b) {
    a.Swap(&b);
  }
  inline void Swap(AddContactReq_Phone* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AddContactReq_Phone* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline AddContactReq_Phone* New() const final {
    return CreateMaybeMessage<AddContactReq_Phone>(nullptr);
  }

  AddContactReq_Phone* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<AddContactReq_Phone>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const AddContactReq_Phone& from);
  void MergeFrom(const AddContactReq_Phone& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AddContactReq_Phone* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "add_contact_req.AddContactReq.Phone";
  }
  protected:
  explicit AddContactReq_Phone(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_add_5fcontact_5frequest_2eproto);
    return ::descriptor_table_add_5fcontact_5frequest_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef AddContactReq_Phone_PhoneType PhoneType;
  static constexpr PhoneType MP =
    AddContactReq_Phone_PhoneType_MP;
  static constexpr PhoneType TEL =
    AddContactReq_Phone_PhoneType_TEL;
  static inline bool PhoneType_IsValid(int value) {
    return AddContactReq_Phone_PhoneType_IsValid(value);
  }
  static constexpr PhoneType PhoneType_MIN =
    AddContactReq_Phone_PhoneType_PhoneType_MIN;
  static constexpr PhoneType PhoneType_MAX =
    AddContactReq_Phone_PhoneType_PhoneType_MAX;
  static constexpr int PhoneType_ARRAYSIZE =
    AddContactReq_Phone_PhoneType_PhoneType_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  PhoneType_descriptor() {
    return AddContactReq_Phone_PhoneType_descriptor();
  }
  template<typename T>
  static inline const std::string& PhoneType_Name(T enum_t_value) {
    static_assert(::std::is_same<T, PhoneType>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function PhoneType_Name.");
    return AddContactReq_Phone_PhoneType_Name(enum_t_value);
  }
  static inline bool PhoneType_Parse(const std::string& name,
      PhoneType* value) {
    return AddContactReq_Phone_PhoneType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kNumberFieldNumber = 1,
    kTypeFieldNumber = 2,
  };
  // string number = 1;
  void clear_number();
  const std::string& number() const;
  void set_number(const std::string& value);
  void set_number(std::string&& value);
  void set_number(const char* value);
  void set_number(const char* value, size_t size);
  std::string* mutable_number();
  std::string* release_number();
  void set_allocated_number(std::string* number);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_number();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_number(
      std::string* number);
  private:
  const std::string& _internal_number() const;
  void _internal_set_number(const std::string& value);
  std::string* _internal_mutable_number();
  public:

  // .add_contact_req.AddContactReq.Phone.PhoneType type = 2;
  void clear_type();
  ::add_contact_req::AddContactReq_Phone_PhoneType type() const;
  void set_type(::add_contact_req::AddContactReq_Phone_PhoneType value);
  private:
  ::add_contact_req::AddContactReq_Phone_PhoneType _internal_type() const;
  void _internal_set_type(::add_contact_req::AddContactReq_Phone_PhoneType value);
  public:

  // @@protoc_insertion_point(class_scope:add_contact_req.AddContactReq.Phone)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr number_;
  int type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_add_5fcontact_5frequest_2eproto;
};
// -------------------------------------------------------------------

class AddContactReq_RemarkEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<AddContactReq_RemarkEntry_DoNotUse, 
    std::string, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    0 > {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<AddContactReq_RemarkEntry_DoNotUse, 
    std::string, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    0 > SuperType;
  AddContactReq_RemarkEntry_DoNotUse();
  AddContactReq_RemarkEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const AddContactReq_RemarkEntry_DoNotUse& other);
  static const AddContactReq_RemarkEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const AddContactReq_RemarkEntry_DoNotUse*>(&_AddContactReq_RemarkEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "add_contact_req.AddContactReq.RemarkEntry.key");
 }
  static bool ValidateValue(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "add_contact_req.AddContactReq.RemarkEntry.value");
 }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_add_5fcontact_5frequest_2eproto);
    return ::descriptor_table_add_5fcontact_5frequest_2eproto.file_level_metadata[1];
  }

  public:
};

// -------------------------------------------------------------------

class AddContactReq PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:add_contact_req.AddContactReq) */ {
 public:
  inline AddContactReq() : AddContactReq(nullptr) {};
  virtual ~AddContactReq();

  AddContactReq(const AddContactReq& from);
  AddContactReq(AddContactReq&& from) noexcept
    : AddContactReq() {
    *this = ::std::move(from);
  }

  inline AddContactReq& operator=(const AddContactReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline AddContactReq& operator=(AddContactReq&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const AddContactReq& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AddContactReq* internal_default_instance() {
    return reinterpret_cast<const AddContactReq*>(
               &_AddContactReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(AddContactReq& a, AddContactReq& b) {
    a.Swap(&b);
  }
  inline void Swap(AddContactReq* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AddContactReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline AddContactReq* New() const final {
    return CreateMaybeMessage<AddContactReq>(nullptr);
  }

  AddContactReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<AddContactReq>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const AddContactReq& from);
  void MergeFrom(const AddContactReq& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AddContactReq* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "add_contact_req.AddContactReq";
  }
  protected:
  explicit AddContactReq(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_add_5fcontact_5frequest_2eproto);
    return ::descriptor_table_add_5fcontact_5frequest_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef AddContactReq_Phone Phone;

  // accessors -------------------------------------------------------

  enum : int {
    kPhoneNumberFieldNumber = 3,
    kRemarkFieldNumber = 4,
    kNameFieldNumber = 1,
    kAgeFieldNumber = 2,
  };
  // repeated .add_contact_req.AddContactReq.Phone phone_number = 3;
  int phone_number_size() const;
  private:
  int _internal_phone_number_size() const;
  public:
  void clear_phone_number();
  ::add_contact_req::AddContactReq_Phone* mutable_phone_number(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::add_contact_req::AddContactReq_Phone >*
      mutable_phone_number();
  private:
  const ::add_contact_req::AddContactReq_Phone& _internal_phone_number(int index) const;
  ::add_contact_req::AddContactReq_Phone* _internal_add_phone_number();
  public:
  const ::add_contact_req::AddContactReq_Phone& phone_number(int index) const;
  ::add_contact_req::AddContactReq_Phone* add_phone_number();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::add_contact_req::AddContactReq_Phone >&
      phone_number() const;

  // map<string, string> remark = 4;
  int remark_size() const;
  private:
  int _internal_remark_size() const;
  public:
  void clear_remark();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
      _internal_remark() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
      _internal_mutable_remark();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
      remark() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
      mutable_remark();

  // string name = 1;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_name();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_name(
      std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // int32 age = 2;
  void clear_age();
  ::PROTOBUF_NAMESPACE_ID::int32 age() const;
  void set_age(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_age() const;
  void _internal_set_age(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:add_contact_req.AddContactReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::add_contact_req::AddContactReq_Phone > phone_number_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      AddContactReq_RemarkEntry_DoNotUse,
      std::string, std::string,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      0 > remark_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::int32 age_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_add_5fcontact_5frequest_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AddContactReq_Phone

// string number = 1;
inline void AddContactReq_Phone::clear_number() {
  number_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& AddContactReq_Phone::number() const {
  // @@protoc_insertion_point(field_get:add_contact_req.AddContactReq.Phone.number)
  return _internal_number();
}
inline void AddContactReq_Phone::set_number(const std::string& value) {
  _internal_set_number(value);
  // @@protoc_insertion_point(field_set:add_contact_req.AddContactReq.Phone.number)
}
inline std::string* AddContactReq_Phone::mutable_number() {
  // @@protoc_insertion_point(field_mutable:add_contact_req.AddContactReq.Phone.number)
  return _internal_mutable_number();
}
inline const std::string& AddContactReq_Phone::_internal_number() const {
  return number_.Get();
}
inline void AddContactReq_Phone::_internal_set_number(const std::string& value) {
  
  number_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void AddContactReq_Phone::set_number(std::string&& value) {
  
  number_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:add_contact_req.AddContactReq.Phone.number)
}
inline void AddContactReq_Phone::set_number(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  number_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:add_contact_req.AddContactReq.Phone.number)
}
inline void AddContactReq_Phone::set_number(const char* value,
    size_t size) {
  
  number_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:add_contact_req.AddContactReq.Phone.number)
}
inline std::string* AddContactReq_Phone::_internal_mutable_number() {
  
  return number_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* AddContactReq_Phone::release_number() {
  // @@protoc_insertion_point(field_release:add_contact_req.AddContactReq.Phone.number)
  return number_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void AddContactReq_Phone::set_allocated_number(std::string* number) {
  if (number != nullptr) {
    
  } else {
    
  }
  number_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), number,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:add_contact_req.AddContactReq.Phone.number)
}
inline std::string* AddContactReq_Phone::unsafe_arena_release_number() {
  // @@protoc_insertion_point(field_unsafe_arena_release:add_contact_req.AddContactReq.Phone.number)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return number_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void AddContactReq_Phone::unsafe_arena_set_allocated_number(
    std::string* number) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (number != nullptr) {
    
  } else {
    
  }
  number_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      number, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:add_contact_req.AddContactReq.Phone.number)
}

// .add_contact_req.AddContactReq.Phone.PhoneType type = 2;
inline void AddContactReq_Phone::clear_type() {
  type_ = 0;
}
inline ::add_contact_req::AddContactReq_Phone_PhoneType AddContactReq_Phone::_internal_type() const {
  return static_cast< ::add_contact_req::AddContactReq_Phone_PhoneType >(type_);
}
inline ::add_contact_req::AddContactReq_Phone_PhoneType AddContactReq_Phone::type() const {
  // @@protoc_insertion_point(field_get:add_contact_req.AddContactReq.Phone.type)
  return _internal_type();
}
inline void AddContactReq_Phone::_internal_set_type(::add_contact_req::AddContactReq_Phone_PhoneType value) {
  
  type_ = value;
}
inline void AddContactReq_Phone::set_type(::add_contact_req::AddContactReq_Phone_PhoneType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:add_contact_req.AddContactReq.Phone.type)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// AddContactReq

// string name = 1;
inline void AddContactReq::clear_name() {
  name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& AddContactReq::name() const {
  // @@protoc_insertion_point(field_get:add_contact_req.AddContactReq.name)
  return _internal_name();
}
inline void AddContactReq::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:add_contact_req.AddContactReq.name)
}
inline std::string* AddContactReq::mutable_name() {
  // @@protoc_insertion_point(field_mutable:add_contact_req.AddContactReq.name)
  return _internal_mutable_name();
}
inline const std::string& AddContactReq::_internal_name() const {
  return name_.Get();
}
inline void AddContactReq::_internal_set_name(const std::string& value) {
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void AddContactReq::set_name(std::string&& value) {
  
  name_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:add_contact_req.AddContactReq.name)
}
inline void AddContactReq::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:add_contact_req.AddContactReq.name)
}
inline void AddContactReq::set_name(const char* value,
    size_t size) {
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:add_contact_req.AddContactReq.name)
}
inline std::string* AddContactReq::_internal_mutable_name() {
  
  return name_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* AddContactReq::release_name() {
  // @@protoc_insertion_point(field_release:add_contact_req.AddContactReq.name)
  return name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void AddContactReq::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:add_contact_req.AddContactReq.name)
}
inline std::string* AddContactReq::unsafe_arena_release_name() {
  // @@protoc_insertion_point(field_unsafe_arena_release:add_contact_req.AddContactReq.name)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return name_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void AddContactReq::unsafe_arena_set_allocated_name(
    std::string* name) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (name != nullptr) {
    
  } else {
    
  }
  name_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      name, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:add_contact_req.AddContactReq.name)
}

// int32 age = 2;
inline void AddContactReq::clear_age() {
  age_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 AddContactReq::_internal_age() const {
  return age_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 AddContactReq::age() const {
  // @@protoc_insertion_point(field_get:add_contact_req.AddContactReq.age)
  return _internal_age();
}
inline void AddContactReq::_internal_set_age(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  age_ = value;
}
inline void AddContactReq::set_age(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_age(value);
  // @@protoc_insertion_point(field_set:add_contact_req.AddContactReq.age)
}

// repeated .add_contact_req.AddContactReq.Phone phone_number = 3;
inline int AddContactReq::_internal_phone_number_size() const {
  return phone_number_.size();
}
inline int AddContactReq::phone_number_size() const {
  return _internal_phone_number_size();
}
inline void AddContactReq::clear_phone_number() {
  phone_number_.Clear();
}
inline ::add_contact_req::AddContactReq_Phone* AddContactReq::mutable_phone_number(int index) {
  // @@protoc_insertion_point(field_mutable:add_contact_req.AddContactReq.phone_number)
  return phone_number_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::add_contact_req::AddContactReq_Phone >*
AddContactReq::mutable_phone_number() {
  // @@protoc_insertion_point(field_mutable_list:add_contact_req.AddContactReq.phone_number)
  return &phone_number_;
}
inline const ::add_contact_req::AddContactReq_Phone& AddContactReq::_internal_phone_number(int index) const {
  return phone_number_.Get(index);
}
inline const ::add_contact_req::AddContactReq_Phone& AddContactReq::phone_number(int index) const {
  // @@protoc_insertion_point(field_get:add_contact_req.AddContactReq.phone_number)
  return _internal_phone_number(index);
}
inline ::add_contact_req::AddContactReq_Phone* AddContactReq::_internal_add_phone_number() {
  return phone_number_.Add();
}
inline ::add_contact_req::AddContactReq_Phone* AddContactReq::add_phone_number() {
  // @@protoc_insertion_point(field_add:add_contact_req.AddContactReq.phone_number)
  return _internal_add_phone_number();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::add_contact_req::AddContactReq_Phone >&
AddContactReq::phone_number() const {
  // @@protoc_insertion_point(field_list:add_contact_req.AddContactReq.phone_number)
  return phone_number_;
}

// map<string, string> remark = 4;
inline int AddContactReq::_internal_remark_size() const {
  return remark_.size();
}
inline int AddContactReq::remark_size() const {
  return _internal_remark_size();
}
inline void AddContactReq::clear_remark() {
  remark_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
AddContactReq::_internal_remark() const {
  return remark_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
AddContactReq::remark() const {
  // @@protoc_insertion_point(field_map:add_contact_req.AddContactReq.remark)
  return _internal_remark();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
AddContactReq::_internal_mutable_remark() {
  return remark_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
AddContactReq::mutable_remark() {
  // @@protoc_insertion_point(field_mutable_map:add_contact_req.AddContactReq.remark)
  return _internal_mutable_remark();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace add_contact_req

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::add_contact_req::AddContactReq_Phone_PhoneType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::add_contact_req::AddContactReq_Phone_PhoneType>() {
  return ::add_contact_req::AddContactReq_Phone_PhoneType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_add_5fcontact_5frequest_2eproto
