// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: add_contact_response.proto

#include "add_contact_response.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_base_5fresponse_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_BaseResponse_base_5fresponse_2eproto;
namespace add_contact_resp {
class AddContactRepDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<AddContactRep> _instance;
} _AddContactRep_default_instance_;
}  // namespace add_contact_resp
static void InitDefaultsscc_info_AddContactRep_add_5fcontact_5fresponse_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::add_contact_resp::_AddContactRep_default_instance_;
    new (ptr) ::add_contact_resp::AddContactRep();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::add_contact_resp::AddContactRep::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_AddContactRep_add_5fcontact_5fresponse_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_AddContactRep_add_5fcontact_5fresponse_2eproto}, {
      &scc_info_BaseResponse_base_5fresponse_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_add_5fcontact_5fresponse_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_add_5fcontact_5fresponse_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_add_5fcontact_5fresponse_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_add_5fcontact_5fresponse_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::add_contact_resp::AddContactRep, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::add_contact_resp::AddContactRep, base_resp_),
  PROTOBUF_FIELD_OFFSET(::add_contact_resp::AddContactRep, uid_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::add_contact_resp::AddContactRep)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::add_contact_resp::_AddContactRep_default_instance_),
};

const char descriptor_table_protodef_add_5fcontact_5fresponse_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\032add_contact_response.proto\022\020add_contac"
  "t_resp\032\023base_response.proto\"L\n\rAddContac"
  "tRep\022.\n\tbase_resp\030\001 \001(\0132\033.base_response."
  "BaseResponse\022\013\n\003uid\030\002 \001(\tb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_add_5fcontact_5fresponse_2eproto_deps[1] = {
  &::descriptor_table_base_5fresponse_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_add_5fcontact_5fresponse_2eproto_sccs[1] = {
  &scc_info_AddContactRep_add_5fcontact_5fresponse_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_add_5fcontact_5fresponse_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_add_5fcontact_5fresponse_2eproto = {
  false, false, descriptor_table_protodef_add_5fcontact_5fresponse_2eproto, "add_contact_response.proto", 153,
  &descriptor_table_add_5fcontact_5fresponse_2eproto_once, descriptor_table_add_5fcontact_5fresponse_2eproto_sccs, descriptor_table_add_5fcontact_5fresponse_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_add_5fcontact_5fresponse_2eproto::offsets,
  file_level_metadata_add_5fcontact_5fresponse_2eproto, 1, file_level_enum_descriptors_add_5fcontact_5fresponse_2eproto, file_level_service_descriptors_add_5fcontact_5fresponse_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_add_5fcontact_5fresponse_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_add_5fcontact_5fresponse_2eproto)), true);
namespace add_contact_resp {

// ===================================================================

void AddContactRep::InitAsDefaultInstance() {
  ::add_contact_resp::_AddContactRep_default_instance_._instance.get_mutable()->base_resp_ = const_cast< ::base_response::BaseResponse*>(
      ::base_response::BaseResponse::internal_default_instance());
}
class AddContactRep::_Internal {
 public:
  static const ::base_response::BaseResponse& base_resp(const AddContactRep* msg);
};

const ::base_response::BaseResponse&
AddContactRep::_Internal::base_resp(const AddContactRep* msg) {
  return *msg->base_resp_;
}
void AddContactRep::clear_base_resp() {
  if (GetArena() == nullptr && base_resp_ != nullptr) {
    delete base_resp_;
  }
  base_resp_ = nullptr;
}
AddContactRep::AddContactRep(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:add_contact_resp.AddContactRep)
}
AddContactRep::AddContactRep(const AddContactRep& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  uid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_uid().empty()) {
    uid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_uid(),
      GetArena());
  }
  if (from._internal_has_base_resp()) {
    base_resp_ = new ::base_response::BaseResponse(*from.base_resp_);
  } else {
    base_resp_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:add_contact_resp.AddContactRep)
}

void AddContactRep::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_AddContactRep_add_5fcontact_5fresponse_2eproto.base);
  uid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  base_resp_ = nullptr;
}

AddContactRep::~AddContactRep() {
  // @@protoc_insertion_point(destructor:add_contact_resp.AddContactRep)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void AddContactRep::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  uid_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete base_resp_;
}

void AddContactRep::ArenaDtor(void* object) {
  AddContactRep* _this = reinterpret_cast< AddContactRep* >(object);
  (void)_this;
}
void AddContactRep::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void AddContactRep::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const AddContactRep& AddContactRep::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_AddContactRep_add_5fcontact_5fresponse_2eproto.base);
  return *internal_default_instance();
}


void AddContactRep::Clear() {
// @@protoc_insertion_point(message_clear_start:add_contact_resp.AddContactRep)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  uid_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  if (GetArena() == nullptr && base_resp_ != nullptr) {
    delete base_resp_;
  }
  base_resp_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AddContactRep::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .base_response.BaseResponse base_resp = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_base_resp(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string uid = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_uid();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "add_contact_resp.AddContactRep.uid"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* AddContactRep::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:add_contact_resp.AddContactRep)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .base_response.BaseResponse base_resp = 1;
  if (this->has_base_resp()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::base_resp(this), target, stream);
  }

  // string uid = 2;
  if (this->uid().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_uid().data(), static_cast<int>(this->_internal_uid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "add_contact_resp.AddContactRep.uid");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_uid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:add_contact_resp.AddContactRep)
  return target;
}

size_t AddContactRep::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:add_contact_resp.AddContactRep)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string uid = 2;
  if (this->uid().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_uid());
  }

  // .base_response.BaseResponse base_resp = 1;
  if (this->has_base_resp()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *base_resp_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void AddContactRep::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:add_contact_resp.AddContactRep)
  GOOGLE_DCHECK_NE(&from, this);
  const AddContactRep* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<AddContactRep>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:add_contact_resp.AddContactRep)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:add_contact_resp.AddContactRep)
    MergeFrom(*source);
  }
}

void AddContactRep::MergeFrom(const AddContactRep& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:add_contact_resp.AddContactRep)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.uid().size() > 0) {
    _internal_set_uid(from._internal_uid());
  }
  if (from.has_base_resp()) {
    _internal_mutable_base_resp()->::base_response::BaseResponse::MergeFrom(from._internal_base_resp());
  }
}

void AddContactRep::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:add_contact_resp.AddContactRep)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AddContactRep::CopyFrom(const AddContactRep& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:add_contact_resp.AddContactRep)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AddContactRep::IsInitialized() const {
  return true;
}

void AddContactRep::InternalSwap(AddContactRep* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  uid_.Swap(&other->uid_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(base_resp_, other->base_resp_);
}

::PROTOBUF_NAMESPACE_ID::Metadata AddContactRep::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace add_contact_resp
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::add_contact_resp::AddContactRep* Arena::CreateMaybeMessage< ::add_contact_resp::AddContactRep >(Arena* arena) {
  return Arena::CreateMessageInternal< ::add_contact_resp::AddContactRep >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
