// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: add_contact_response.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_add_5fcontact_5fresponse_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_add_5fcontact_5fresponse_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "base_response.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_add_5fcontact_5fresponse_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_add_5fcontact_5fresponse_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_add_5fcontact_5fresponse_2eproto;
namespace add_contact_resp {
class AddContactRep;
class AddContactRepDefaultTypeInternal;
extern AddContactRepDefaultTypeInternal _AddContactRep_default_instance_;
}  // namespace add_contact_resp
PROTOBUF_NAMESPACE_OPEN
template<> ::add_contact_resp::AddContactRep* Arena::CreateMaybeMessage<::add_contact_resp::AddContactRep>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace add_contact_resp {

// ===================================================================

class AddContactRep PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:add_contact_resp.AddContactRep) */ {
 public:
  inline AddContactRep() : AddContactRep(nullptr) {};
  virtual ~AddContactRep();

  AddContactRep(const AddContactRep& from);
  AddContactRep(AddContactRep&& from) noexcept
    : AddContactRep() {
    *this = ::std::move(from);
  }

  inline AddContactRep& operator=(const AddContactRep& from) {
    CopyFrom(from);
    return *this;
  }
  inline AddContactRep& operator=(AddContactRep&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const AddContactRep& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AddContactRep* internal_default_instance() {
    return reinterpret_cast<const AddContactRep*>(
               &_AddContactRep_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(AddContactRep& a, AddContactRep& b) {
    a.Swap(&b);
  }
  inline void Swap(AddContactRep* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AddContactRep* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline AddContactRep* New() const final {
    return CreateMaybeMessage<AddContactRep>(nullptr);
  }

  AddContactRep* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<AddContactRep>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const AddContactRep& from);
  void MergeFrom(const AddContactRep& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AddContactRep* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "add_contact_resp.AddContactRep";
  }
  protected:
  explicit AddContactRep(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_add_5fcontact_5fresponse_2eproto);
    return ::descriptor_table_add_5fcontact_5fresponse_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUidFieldNumber = 2,
    kBaseRespFieldNumber = 1,
  };
  // string uid = 2;
  void clear_uid();
  const std::string& uid() const;
  void set_uid(const std::string& value);
  void set_uid(std::string&& value);
  void set_uid(const char* value);
  void set_uid(const char* value, size_t size);
  std::string* mutable_uid();
  std::string* release_uid();
  void set_allocated_uid(std::string* uid);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_uid();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_uid(
      std::string* uid);
  private:
  const std::string& _internal_uid() const;
  void _internal_set_uid(const std::string& value);
  std::string* _internal_mutable_uid();
  public:

  // .base_response.BaseResponse base_resp = 1;
  bool has_base_resp() const;
  private:
  bool _internal_has_base_resp() const;
  public:
  void clear_base_resp();
  const ::base_response::BaseResponse& base_resp() const;
  ::base_response::BaseResponse* release_base_resp();
  ::base_response::BaseResponse* mutable_base_resp();
  void set_allocated_base_resp(::base_response::BaseResponse* base_resp);
  private:
  const ::base_response::BaseResponse& _internal_base_resp() const;
  ::base_response::BaseResponse* _internal_mutable_base_resp();
  public:
  void unsafe_arena_set_allocated_base_resp(
      ::base_response::BaseResponse* base_resp);
  ::base_response::BaseResponse* unsafe_arena_release_base_resp();

  // @@protoc_insertion_point(class_scope:add_contact_resp.AddContactRep)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr uid_;
  ::base_response::BaseResponse* base_resp_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_add_5fcontact_5fresponse_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AddContactRep

// .base_response.BaseResponse base_resp = 1;
inline bool AddContactRep::_internal_has_base_resp() const {
  return this != internal_default_instance() && base_resp_ != nullptr;
}
inline bool AddContactRep::has_base_resp() const {
  return _internal_has_base_resp();
}
inline const ::base_response::BaseResponse& AddContactRep::_internal_base_resp() const {
  const ::base_response::BaseResponse* p = base_resp_;
  return p != nullptr ? *p : *reinterpret_cast<const ::base_response::BaseResponse*>(
      &::base_response::_BaseResponse_default_instance_);
}
inline const ::base_response::BaseResponse& AddContactRep::base_resp() const {
  // @@protoc_insertion_point(field_get:add_contact_resp.AddContactRep.base_resp)
  return _internal_base_resp();
}
inline void AddContactRep::unsafe_arena_set_allocated_base_resp(
    ::base_response::BaseResponse* base_resp) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(base_resp_);
  }
  base_resp_ = base_resp;
  if (base_resp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:add_contact_resp.AddContactRep.base_resp)
}
inline ::base_response::BaseResponse* AddContactRep::release_base_resp() {
  auto temp = unsafe_arena_release_base_resp();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::base_response::BaseResponse* AddContactRep::unsafe_arena_release_base_resp() {
  // @@protoc_insertion_point(field_release:add_contact_resp.AddContactRep.base_resp)
  
  ::base_response::BaseResponse* temp = base_resp_;
  base_resp_ = nullptr;
  return temp;
}
inline ::base_response::BaseResponse* AddContactRep::_internal_mutable_base_resp() {
  
  if (base_resp_ == nullptr) {
    auto* p = CreateMaybeMessage<::base_response::BaseResponse>(GetArena());
    base_resp_ = p;
  }
  return base_resp_;
}
inline ::base_response::BaseResponse* AddContactRep::mutable_base_resp() {
  // @@protoc_insertion_point(field_mutable:add_contact_resp.AddContactRep.base_resp)
  return _internal_mutable_base_resp();
}
inline void AddContactRep::set_allocated_base_resp(::base_response::BaseResponse* base_resp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(base_resp_);
  }
  if (base_resp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(base_resp)->GetArena();
    if (message_arena != submessage_arena) {
      base_resp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, base_resp, submessage_arena);
    }
    
  } else {
    
  }
  base_resp_ = base_resp;
  // @@protoc_insertion_point(field_set_allocated:add_contact_resp.AddContactRep.base_resp)
}

// string uid = 2;
inline void AddContactRep::clear_uid() {
  uid_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& AddContactRep::uid() const {
  // @@protoc_insertion_point(field_get:add_contact_resp.AddContactRep.uid)
  return _internal_uid();
}
inline void AddContactRep::set_uid(const std::string& value) {
  _internal_set_uid(value);
  // @@protoc_insertion_point(field_set:add_contact_resp.AddContactRep.uid)
}
inline std::string* AddContactRep::mutable_uid() {
  // @@protoc_insertion_point(field_mutable:add_contact_resp.AddContactRep.uid)
  return _internal_mutable_uid();
}
inline const std::string& AddContactRep::_internal_uid() const {
  return uid_.Get();
}
inline void AddContactRep::_internal_set_uid(const std::string& value) {
  
  uid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void AddContactRep::set_uid(std::string&& value) {
  
  uid_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:add_contact_resp.AddContactRep.uid)
}
inline void AddContactRep::set_uid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  uid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:add_contact_resp.AddContactRep.uid)
}
inline void AddContactRep::set_uid(const char* value,
    size_t size) {
  
  uid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:add_contact_resp.AddContactRep.uid)
}
inline std::string* AddContactRep::_internal_mutable_uid() {
  
  return uid_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* AddContactRep::release_uid() {
  // @@protoc_insertion_point(field_release:add_contact_resp.AddContactRep.uid)
  return uid_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void AddContactRep::set_allocated_uid(std::string* uid) {
  if (uid != nullptr) {
    
  } else {
    
  }
  uid_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), uid,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:add_contact_resp.AddContactRep.uid)
}
inline std::string* AddContactRep::unsafe_arena_release_uid() {
  // @@protoc_insertion_point(field_unsafe_arena_release:add_contact_resp.AddContactRep.uid)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return uid_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void AddContactRep::unsafe_arena_set_allocated_uid(
    std::string* uid) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (uid != nullptr) {
    
  } else {
    
  }
  uid_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      uid, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:add_contact_resp.AddContactRep.uid)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace add_contact_resp

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_add_5fcontact_5fresponse_2eproto
